# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://www.alx.pl/szkolenia/ci-cd-jenkins/")
    self.driver.set_window_size(1601, 858)
    self.driver.find_element(By.CSS_SELECTOR, ".lp-cityRow:nth-child(2) li:nth-child(3) > a").click()
    self.driver.find_element(By.ID, "id_imie_nazwisko").click()
    self.driver.find_element(By.ID, "id_imie_nazwisko").send_keys("Tomasz Kaniecki")
    self.driver.find_element(By.ID, "id_telefon").click()
    self.driver.find_element(By.ID, "id_telefon").send_keys("531989599")
    self.driver.find_element(By.ID, "id_email").send_keys("biuro@dev-com.pl")
    self.driver.find_element(By.ID, "id_email_ksiegowosc").send_keys("biuro@dev-com.pl")
    self.driver.find_element(By.ID, "id_adres").send_keys("Salata 15")
    self.driver.find_element(By.ID, "id_miejscowosc_kod").send_keys("Smyków")
    dropdown = self.driver.find_element(By.ID, "id_raty_panstwo")
    dropdown.find_element(By.XPATH, "//option[. = '----']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".required:nth-child(9) > .input").click()
    self.driver.find_element(By.ID, "submit_button").click()
  
